---
- name: Deploy Yii2 app on EC2 using Docker Swarm
  hosts: yii2_servers
  become: true

  pre_tasks:
    - name: Remove existing yii2app service if it exists
      command: docker service rm yii2app
      ignore_errors: yes

    - name: Check if yii2app service still exists
      command: docker service ls --filter name=yii2app --format '{{.Name}}'
      register: service_check

    - debug:
        var: service_check.stdout_lines

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Initialize Docker Swarm (if not already)
      shell: |
        if ! docker info | grep -q "Swarm: active"; then
          docker swarm init --advertise-addr {{ ansible_host }}
        else
          echo "Swarm already active"
        fi
      register: swarm_init_result
      changed_when: "'Swarm initialized' in swarm_init_result.stdout"
      failed_when: false

    - name: Login to Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env','DOCKER_USERNAME') }}"
        password: "{{ lookup('env','DOCKER_PASSWORD') }}"

    - name: Pull Yii2 image (optional since Swarm pulls automatically)
      community.docker.docker_image:
        name: viveksharma754/yii2-app
        source: pull
        tag: app

    - name: Deploy Yii2 app as a Docker Swarm service
      command: >
        docker service create
        --name yii2app
        --publish 8081:80
        --replicas 1
        viveksharma754/yii2-app:app
      args:
        creates: /var/lib/docker/swarm
