---
- name: Deploy Yii2 app on EC2 using Docker Swarm
  hosts: yii2_servers
  become: true

  pre_tasks:
    - name: Remove existing yii2app service if it exists
      command: docker service rm yii2app
      ignore_errors: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Initialize Docker Swarm (if not already)
      command: docker swarm init
      register: swarm_init_output
      failed_when: "'Error response from daemon: This node is already part of a swarm' not in swarm_init_output.stderr"
      ignore_errors: yes

    - name: Pull Yii2 image (optional since Swarm pulls automatically)
      community.docker.docker_image:
        name: princeashok/yii2-app
        source: pull
        tag: latest

    - name: Deploy Yii2 app as a Docker Swarm service
      command: >
        docker service create
        --name yii2app
        --publish 8081:80
        --replicas 1
        princeashok/yii2-app:latest
      args:
        creates: /var/lib/docker/swarm  # prevents re-running on every play
