---
- name: Deploy Yii2 app on EC2 using Docker Swarm
  hosts: yii2_servers
  become: true

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Initialize Docker Swarm (if not already)
      shell: |
        docker info | grep -q 'Swarm: active' || docker swarm init
      changed_when: false

    - name: Create stack.yml file
      copy:
        dest: /home/ubuntu/stack.yml
        content: |
          version: "3.8"
          services:
            yii2app:
              image: viveksharma754/yii2-app:latest
              ports:
                - "8081:80"
              restart: always

    - name: Deploy Yii2 app using Docker Stack
      shell: docker stack deploy -c /home/ubuntu/stack.yml yii2app

    - name: Wait for container to be up
      shell: docker service ls | grep yii2app
      register: service_status
      retries: 5
      delay: 5
      until: service_status.rc == 0
