name: Deploy Yii2 App with Docker Swarm

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest

      - name: Deploy on EC2 using Docker Swarm
        uses: actions/checkout@v4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker swarm init || true
            docker service rm yii2-app || true
            docker service create \
              --name yii2-app \
              --publish 8081:80 \
              --replicas 1 \
              ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest
